name: leaf_detector
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  tflite_flutter: ^0.11.0
  image_picker: ^1.1.0
  camera: ^0.11.0
  image: ^4.5.4 # Add this

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: 0.14.4

flutter_icons:
  android: true
  ios: false
  image_path: "assets/launch_image.png"

flutter:
  uses-material-design: true

  assets:
    - assets/cashew_classifier.tflite
    - assets/logo.png
    - assets/cashew_leaf.png
    - assets/app_logo.png
    - assets/main_slide.jpg
    - assets/leaf_banner.jpg
